### ISSUE TITLE
인터페이스

### ISSUE THREAD

**Issue by JustHaWall** [wjdduqtls1517/OpenSourceProject#10]
전체적인 레이아웃 양식이 있으면 좋을 것 같습니다.

**Comment by wjdduqtls1517** [comment]
다른 모바일 애플리케이션처럼 모든 화면 아래에 "이전" 버튼과 "다음" 버튼이 있으면 좋을 것 같습니다.

**Comment by JustHaWall** [comment]
위쪽에는 이 화면이 무엇을 나타내는 화면인지 작성되면 좋을 것 같습니다.

**Comment by semin-go** [comment]
프로젝트 취지에 맞게 버튼이나 문구의 크기와 폰트에 가독성을 부여해야 할 것 같습니다.
