### ISSUE TITLE
초기 화면 성별 선택 관련

### ISSUE THREAD

**Issue by JustHaWall** [wjdduqtls1517/OpenSourceProject#12]
콤보박스로 할 건지 체크 박스로 할 건지, 크기와 위치는 어떻게 할건지 정하면 좋을 것 같습니다.

**Comment by wjdduqtls1517** [comment]
성별은 두 가지 밖에 없으니까 체크 박스가 좋을 것 같습니다.

**Comment by semin-go** [comment]
창에 나이를 입력하는 콤보박스가 함께 들어갈 예정이니, 콤보박스에 사용될 폰트와 크기로 맞추는 게 좋을 것 같습니다.
