### ISSUE TITLE
초기 화면 나이 구현 방법

### ISSUE THREAD

**Issue by JustHaWall** [wjdduqtls1517/OpenSourceProject#13]
콤보박스로 할 건지 체크박스로 할 건지, 연령의 범위는 어떻게 잡을 건지 정하면 좋을 것 같습니다.

**Comment by wjdduqtls1517** [comment]
노인 건강 관리가 주제니까 노인 연령대가 좋을 것 같습니다.

**Comment by JustHaWall** [comment]
10년씩 나이대를 묶으면 좋을 것 같습니다.

**Comment by semin-go** [comment]
10년씩 나이대를 묶으려면 체크박스보다 콤보박스가 접근하기 편할 것 같습니다.
