### ISSUE TITLE
질병 선택 화면 관련

### ISSUE THREAD

**Issue by JustHaWall** [wjdduqtls1517/OpenSourceProject#15]
콤보박스로 할지, 체크박스로 할지, 콤보박스라면 좌표와 크기는 어떻게 할 것인지 체크박스라면 몇행 몇열로 배치 할지 정하면 좋을 것 같습니다.

**Comment by wjdduqtls1517** [comment]
콤보박스로 하면 중복선택할 때 어려움이 있을 것 같습니다.

**Comment by JustHaWall** [comment]
중복 선택을 할 수 있는 방법으로 하면 좋을 것 같습니다.

**Comment by wjdduqtls1517** [comment]
질병이 총 21가지니까 7행 3열로 배치하면 좋을 것 같습니다.

**Comment by semin-go** [comment]
체크 박스로 배치하면 가독성이 떨어질 수 있지만, 제일 직관적으로 선택할 수 있어 체크 박스가 적합한 것 같습니다.
