### ISSUE TITLE
프로젝트 주제 정하기

### ISSUE THREAD

**Issue by wjdduqtls1517** [wjdduqtls1517/OpenSourceProject#2]
# 프로젝트 주제
1. 건강 관련 테마

2. 프로그램에 포함될 내용

3. 차별성

**Comment by wjdduqtls1517** [comment]
건강 관련 테마로 노인 건강 관리 프로그램이면 좋을 것 같습니다.

**Comment by semin-go** [comment]
프로젝트 차별성을 위해 앱의 단순화와 접근성을 높이는 게 좋을 것 같습니다.
(대다수의 노인들이 앱 사용에 어려움을 겪고 있음)

**Comment by JustHaWall** [comment]
질병에 대한 복약 시기나 운동과 같은 생활 습관에 대한 정보를 제공하는 프로그램으로 하는게 좋을거 같습니다.
