### ISSUE TITLE
질병 선택 이후 화면 디자인

### ISSUE THREAD

**Issue by wjdduqtls1517** [wjdduqtls1517/OpenSourceProject#21]
#18 질병 선택 다음 화면은 어떻게 구성하면 좋을 지 의견 주시면 감사하겠습니다.

**Comment by wjdduqtls1517** [comment]
상단에는 사용자 정보(성별, 나이)가 있으면 사용자가 혼란을 겪지 않을 것 같습니다.

**Comment by semin-go** [comment]
사용자 정보를 토대로 사용자의 정보에 맞는 주의해야할 병들에 대해 설명 및 언급하는 것이 좋을 것 같습니다.

**Comment by JustHaWall** [comment]
사용자가 선택한 질병들과 조심해야할 질병이 들어가면 좋을 것 같습니다.
