### ISSUE TITLE
수집한 질병 데이터 저장 방식

### ISSUE THREAD

**Issue by semin-go** [wjdduqtls1517/OpenSourceProject#24]
데이터들을 어떻게 저장하고, 어떻게 프로그램에 연결을 할지 정해야 할 것 같습니다.

**Comment by wjdduqtls1517** [comment]
데이터 저장은 텍스트 파일로 하는게 좋을 것 같습니다.

**Comment by semin-go** [comment]
텍스트 파일이 사용할 저희가 사용할 수 있는 데이터 처리 방식 중 제일 간편한 것 같습니다.
