### ISSUE TITLE
개발 Tool 결정

### ISSUE THREAD

**Issue by JustHaWall** [wjdduqtls1517/OpenSourceProject#3]
# 개발 Tool

저희 개발 Tool은 어떤걸 사용하는게 좋을까요?

**Comment by wjdduqtls1517** [comment]
파이썬 Tkinter 사용하면 좋을 것 같습니다.

**Comment by semin-go** [comment]
c++의 opencv를 사용하는 것이 좋을 것 같습니다.

**Comment by JustHaWall** [comment]
Python에 있는 'pyqt5' 라이브러리를 사용해서 구체적인 GUI를 만들기를 제안드립니다.

**Comment by wjdduqtls1517** [comment]
좋을 것 같습니다.
