### ISSUE TITLE
텍스트 파일 업로드

### ISSUE THREAD

**Issue by semin-go** [wjdduqtls1517/OpenSourceProject#62]
텍스트 파일을 git으로 커밋을 하는 과정에서 텍스트 파일의 제목이 한글+특수문자인 경우 텍스트 파일과 제목이 깨지는 현상이 있습니다.
해결 방안을 아시는 분은 해결 부탁드립니다.

**Comment by semin-go** [comment]
수업시간에 배운 putty를 통해 리눅스 환경에서 커밋을 진행하였습니다.

**Comment by wjdduqtls1517** [comment]
파이참에서 깃허브와 연동할 수 있는 기능을 제공하고 있어서 깃허브에서 파일 커밋하면 될 것 같습니다.
