### ISSUE TITLE
노인성질환 데이터

### ISSUE THREAD

**Issue by wjdduqtls1517** [wjdduqtls1517/OpenSourceProject#7]
# 노인성질환 데이터
질환 데이터는 어떻게 구하는게 좋을까요?

**Comment by JustHaWall** [comment]
인터넷이나 질병관리청 같은 사이트들을 찾아보면 좋을 것 같습니다.

**Comment by wjdduqtls1517** [comment]
신뢰성이 있는 권위있는 사이트로 선정하면 좋을 것 같습니다.

**Comment by JustHaWall** [comment]
국가 기관으로 하면 좋을 것 같습니다.

**Comment by wjdduqtls1517** [comment]
질환 갯수는 20~25개로 하면 적당할 것 같습니다.

**Comment by semin-go** [comment]
https://www.gbmg.go.kr/portal/contents.do?mId=0404030100
문경시청 홈페이지의 노인성 질환 관리 페이지에서 참고하면 좋을 것 같습니다.
