### ISSUE TITLE
사용자의 회원 가입 및 입력정보

### ISSUE THREAD

**Issue by semin-go** [wjdduqtls1517/OpenSourceProject#8]
어떤 정보를 수집하고, 회원 가입 기능을 어떻게 구현

**Comment by wjdduqtls1517** [comment]
성별에 따라 걸리는 질병이 다를 수 있기 때문에 성별을 선택할 수 있어야 할 것 같습니다.

**Comment by semin-go** [comment]
프로젝트의 취지가 노인들을 대상으로 하기 때문에 최소한의 정보 입력을 요구하는 것이 좋을 것 같습니다.

**Comment by JustHaWall** [comment]
그럼 성별과 나이대 정도만 입력하는게 좋을 것 같습니다.
