### ISSUE TITLE
각 질병, 질환에 대한 정보

### ISSUE THREAD

**Issue by JustHaWall** [wjdduqtls1517/OpenSourceProject#9]
각 질병이나 질환에 대한 어떠한 점을 조사할지 궁금합니다.
ex) 지방간에 대하여 조사한다면 지방간의 증상, 치료법 등등 어떤 것들을 조사해서 기입할지.

**Comment by wjdduqtls1517** [comment]
질병에 대한 정의가 먼저 설명되어야 할 것 같습니다.

**Comment by semin-go** [comment]
질병을 유발하는 원인에 대한 설명이 필요할 것 같습니다.
또한 그 원인에 따른 예방법도 추가적인 조사가 필요합니다.

**Comment by JustHaWall** [comment]
질병의 정의, 원인, 증상, 예방법 등이 들어가면 좋을 것 같습니다.
